2023-02-11 12:35:25.560 - INFO - 7299 - azureml.train.automl._local_managed_utils.is_docker_installed:354 - Docker is installed with Docker version 20.10.22+azure-1, build 3a2c30b63ab20acfcc3f3550ea756a0561655a77
.
2023-02-11 12:35:25.563 - INFO - 7299 - azureml.train.automl.automlconfig._start_execution:229 - Submitting remote.
2023-02-11 12:49:55.307 - INFO - 7299 - azureml.train.automl.run._log_activity:55 - ActivityStarted: GetOutput
2023-02-11 12:49:55.335 - INFO - 7299 - azureml.train.automl.run._log_activity:55 - ActivityStarted: GetOutput
2023-02-11 12:49:55.359 - INFO - 7299 - azureml.train.automl.run._log_activity:55 - ActivityStarted: GetChildren
2023-02-11 12:49:55.502 - INFO - 7299 - azureml.train.automl.run._log_activity:89 - ActivityCompleted: Activity=GetChildren, HowEnded=Success, Duration=142.84[ms]
2023-02-11 12:49:55.574 - INFO - 7299 - azureml.train.automl.run._log_activity:89 - ActivityCompleted: Activity=GetOutput, HowEnded=Success, Duration=239.14[ms]
2023-02-11 12:49:55.579 - INFO - 7299 - azureml.train.automl._model_download_utilities._log_activity:55 - ActivityStarted: DownloadModel
2023-02-11 12:49:57.607 - CRITICAL - 7299 - azureml.train.automl._model_download_utilities.log_traceback:227 - Type: Unclassified
Class: PermissionError
Message: [Errno 1] Operation not permitted: '/anaconda/envs/azureml_py38/lib/python3.8/site-packages/nimbusml/internal/libs/pybridge.so'
Traceback:
  File "_model_download_utilities.py", line 172, in _load_automl_model
    fitted_model = pickle.load(model_file)  # type: Optional[Any]
  File "__init__.py", line 8, in <module>
    from .data_transformer import DataTransformer, TransformerAndMapper
  File "data_transformer.py", line 56, in <module>
    from azureml.automl.runtime.featurizer.transformer.categorical import LabelEncoderTransformer
  File "__init__.py", line 7, in <module>
    from .categorical import CategoricalFeaturizers, CatImputer, LabelEncoderTransformer, \
  File "__init__.py", line 7, in <module>
    from .labelencoder_transformer import LabelEncoderTransformer
  File "labelencoder_transformer.py", line 5, in <module>
    from azureml.training.tabular.featurization.categorical.labelencoder_transformer import LabelEncoderTransformer
  File "labelencoder_transformer.py", line 12, in <module>
    from ...models._abstract_model_wrapper import _AbstractModelWrapper
  File "__init__.py", line 6, in <module>
    from .forecasting_pipeline_wrapper import RegressionPipeline, ForecastingPipelineWrapper
  File "forecasting_pipeline_wrapper.py", line 10, in <module>
    import nimbusml
  File "__init__.py", line 33, in <module>
    os.chmod(dotso, 0o755)

ExceptionTarget: Unspecified
2023-02-11 12:49:57.798 - CRITICAL - 7299 - azureml.train.automl._model_download_utilities.log_traceback:227 - Type: Unclassified
Class: PermissionError
Message: [Errno 1] Operation not permitted: '/anaconda/envs/azureml_py38/lib/python3.8/site-packages/nimbusml/internal/libs/pybridge.so'
Traceback:
  File "telemetry_activity_logger.py", line 58, in _log_activity
    yield
  File "_model_download_utilities.py", line 80, in _download_automl_model
    model = _load_automl_model(model_path, suffix)
  File "_model_download_utilities.py", line 172, in _load_automl_model
    fitted_model = pickle.load(model_file)  # type: Optional[Any]
  File "__init__.py", line 8, in <module>
    from .data_transformer import DataTransformer, TransformerAndMapper
  File "data_transformer.py", line 56, in <module>
    from azureml.automl.runtime.featurizer.transformer.categorical import LabelEncoderTransformer
  File "__init__.py", line 7, in <module>
    from .categorical import CategoricalFeaturizers, CatImputer, LabelEncoderTransformer, \
  File "__init__.py", line 7, in <module>
    from .labelencoder_transformer import LabelEncoderTransformer
  File "labelencoder_transformer.py", line 5, in <module>
    from azureml.training.tabular.featurization.categorical.labelencoder_transformer import LabelEncoderTransformer
  File "labelencoder_transformer.py", line 12, in <module>
    from ...models._abstract_model_wrapper import _AbstractModelWrapper
  File "__init__.py", line 6, in <module>
    from .forecasting_pipeline_wrapper import RegressionPipeline, ForecastingPipelineWrapper
  File "forecasting_pipeline_wrapper.py", line 10, in <module>
    import nimbusml
  File "__init__.py", line 33, in <module>
    os.chmod(dotso, 0o755)

ExceptionTarget: Unspecified
2023-02-11 12:49:57.810 - INFO - 7299 - azureml.train.automl._model_download_utilities._log_activity:89 - ActivityCompleted: Activity=DownloadModel, HowEnded=Failure, Duration=2230.36[ms]
2023-02-11 12:49:57.847 - CRITICAL - 7299 - azureml.train.automl.run.log_traceback:227 - Type: Unclassified
Class: PermissionError
Message: [Errno 1] Operation not permitted: '/anaconda/envs/azureml_py38/lib/python3.8/site-packages/nimbusml/internal/libs/pybridge.so'
Traceback:
  File "telemetry_activity_logger.py", line 58, in _log_activity
    yield
  File "run.py", line 718, in get_output
    fitted_model = _download_automl_model(curr_run, model_name)
  File "_model_download_utilities.py", line 80, in _download_automl_model
    model = _load_automl_model(model_path, suffix)
  File "_model_download_utilities.py", line 172, in _load_automl_model
    fitted_model = pickle.load(model_file)  # type: Optional[Any]
  File "__init__.py", line 8, in <module>
    from .data_transformer import DataTransformer, TransformerAndMapper
  File "data_transformer.py", line 56, in <module>
    from azureml.automl.runtime.featurizer.transformer.categorical import LabelEncoderTransformer
  File "__init__.py", line 7, in <module>
    from .categorical import CategoricalFeaturizers, CatImputer, LabelEncoderTransformer, \
  File "__init__.py", line 7, in <module>
    from .labelencoder_transformer import LabelEncoderTransformer
  File "labelencoder_transformer.py", line 5, in <module>
    from azureml.training.tabular.featurization.categorical.labelencoder_transformer import LabelEncoderTransformer
  File "labelencoder_transformer.py", line 12, in <module>
    from ...models._abstract_model_wrapper import _AbstractModelWrapper
  File "__init__.py", line 6, in <module>
    from .forecasting_pipeline_wrapper import RegressionPipeline, ForecastingPipelineWrapper
  File "forecasting_pipeline_wrapper.py", line 10, in <module>
    import nimbusml
  File "__init__.py", line 33, in <module>
    os.chmod(dotso, 0o755)

ExceptionTarget: Unspecified
2023-02-11 12:49:57.848 - INFO - 7299 - azureml.train.automl.run._log_activity:89 - ActivityCompleted: Activity=GetOutput, HowEnded=Failure, Duration=2540.6[ms]
2023-02-11 12:55:04.229 - INFO - 7299 - azureml.train.automl.run._log_activity:55 - ActivityStarted: GetOutput
2023-02-11 12:55:04.250 - INFO - 7299 - azureml.train.automl.run._log_activity:55 - ActivityStarted: GetOutput
2023-02-11 12:55:04.269 - INFO - 7299 - azureml.train.automl.run._log_activity:55 - ActivityStarted: GetChildren
2023-02-11 12:55:04.430 - INFO - 7299 - azureml.train.automl.run._log_activity:89 - ActivityCompleted: Activity=GetChildren, HowEnded=Success, Duration=161.42[ms]
2023-02-11 12:55:04.498 - INFO - 7299 - azureml.train.automl.run._log_activity:89 - ActivityCompleted: Activity=GetOutput, HowEnded=Success, Duration=247.99[ms]
2023-02-11 12:55:04.498 - INFO - 7299 - azureml.train.automl._model_download_utilities._log_activity:55 - ActivityStarted: DownloadModel
2023-02-11 12:55:05.085 - CRITICAL - 7299 - azureml.train.automl._model_download_utilities.log_traceback:227 - Type: Unclassified
Class: PermissionError
Message: [Errno 1] Operation not permitted: '/anaconda/envs/azureml_py38/lib/python3.8/site-packages/nimbusml/internal/libs/pybridge.so'
Traceback:
  File "_model_download_utilities.py", line 172, in _load_automl_model
    fitted_model = pickle.load(model_file)  # type: Optional[Any]
  File "__init__.py", line 8, in <module>
    from .data_transformer import DataTransformer, TransformerAndMapper
  File "data_transformer.py", line 56, in <module>
    from azureml.automl.runtime.featurizer.transformer.categorical import LabelEncoderTransformer
  File "__init__.py", line 7, in <module>
    from .categorical import CategoricalFeaturizers, CatImputer, LabelEncoderTransformer, \
  File "__init__.py", line 8, in <module>
    from .categorical_featurizers import CategoricalFeaturizers
  File "categorical_featurizers.py", line 8, in <module>
    from nimbusml.feature_extraction.categorical import OneHotVectorizer as NimbusMLOneHotVectorizer
  File "__init__.py", line 33, in <module>
    os.chmod(dotso, 0o755)

ExceptionTarget: Unspecified
2023-02-11 12:55:05.278 - CRITICAL - 7299 - azureml.train.automl._model_download_utilities.log_traceback:227 - Type: Unclassified
Class: PermissionError
Message: [Errno 1] Operation not permitted: '/anaconda/envs/azureml_py38/lib/python3.8/site-packages/nimbusml/internal/libs/pybridge.so'
Traceback:
  File "telemetry_activity_logger.py", line 58, in _log_activity
    yield
  File "_model_download_utilities.py", line 80, in _download_automl_model
    model = _load_automl_model(model_path, suffix)
  File "_model_download_utilities.py", line 172, in _load_automl_model
    fitted_model = pickle.load(model_file)  # type: Optional[Any]
  File "__init__.py", line 8, in <module>
    from .data_transformer import DataTransformer, TransformerAndMapper
  File "data_transformer.py", line 56, in <module>
    from azureml.automl.runtime.featurizer.transformer.categorical import LabelEncoderTransformer
  File "__init__.py", line 7, in <module>
    from .categorical import CategoricalFeaturizers, CatImputer, LabelEncoderTransformer, \
  File "__init__.py", line 8, in <module>
    from .categorical_featurizers import CategoricalFeaturizers
  File "categorical_featurizers.py", line 8, in <module>
    from nimbusml.feature_extraction.categorical import OneHotVectorizer as NimbusMLOneHotVectorizer
  File "__init__.py", line 33, in <module>
    os.chmod(dotso, 0o755)

ExceptionTarget: Unspecified
2023-02-11 12:55:05.278 - INFO - 7299 - azureml.train.automl._model_download_utilities._log_activity:89 - ActivityCompleted: Activity=DownloadModel, HowEnded=Failure, Duration=779.81[ms]
2023-02-11 12:55:05.279 - CRITICAL - 7299 - azureml.train.automl.run.log_traceback:227 - Type: Unclassified
Class: PermissionError
Message: [Errno 1] Operation not permitted: '/anaconda/envs/azureml_py38/lib/python3.8/site-packages/nimbusml/internal/libs/pybridge.so'
Traceback:
  File "telemetry_activity_logger.py", line 58, in _log_activity
    yield
  File "run.py", line 718, in get_output
    fitted_model = _download_automl_model(curr_run, model_name)
  File "_model_download_utilities.py", line 80, in _download_automl_model
    model = _load_automl_model(model_path, suffix)
  File "_model_download_utilities.py", line 172, in _load_automl_model
    fitted_model = pickle.load(model_file)  # type: Optional[Any]
  File "__init__.py", line 8, in <module>
    from .data_transformer import DataTransformer, TransformerAndMapper
  File "data_transformer.py", line 56, in <module>
    from azureml.automl.runtime.featurizer.transformer.categorical import LabelEncoderTransformer
  File "__init__.py", line 7, in <module>
    from .categorical import CategoricalFeaturizers, CatImputer, LabelEncoderTransformer, \
  File "__init__.py", line 8, in <module>
    from .categorical_featurizers import CategoricalFeaturizers
  File "categorical_featurizers.py", line 8, in <module>
    from nimbusml.feature_extraction.categorical import OneHotVectorizer as NimbusMLOneHotVectorizer
  File "__init__.py", line 33, in <module>
    os.chmod(dotso, 0o755)

ExceptionTarget: Unspecified
2023-02-11 12:55:05.279 - INFO - 7299 - azureml.train.automl.run._log_activity:89 - ActivityCompleted: Activity=GetOutput, HowEnded=Failure, Duration=1049.41[ms]
2023-02-11 13:11:52.405 - INFO - 7299 - azureml.train.automl.run._log_activity:55 - ActivityStarted: GetOutput
2023-02-11 13:11:52.427 - INFO - 7299 - azureml.train.automl.run._log_activity:55 - ActivityStarted: GetOutput
2023-02-11 13:11:52.445 - INFO - 7299 - azureml.train.automl.run._log_activity:55 - ActivityStarted: GetChildren
2023-02-11 13:11:52.674 - INFO - 7299 - azureml.train.automl.run._log_activity:89 - ActivityCompleted: Activity=GetChildren, HowEnded=Success, Duration=228.6[ms]
2023-02-11 13:11:52.774 - INFO - 7299 - azureml.train.automl.run._log_activity:89 - ActivityCompleted: Activity=GetOutput, HowEnded=Success, Duration=347.56[ms]
2023-02-11 13:11:52.775 - INFO - 7299 - azureml.train.automl._model_download_utilities._log_activity:55 - ActivityStarted: DownloadModel
2023-02-11 13:11:53.497 - CRITICAL - 7299 - azureml.train.automl._model_download_utilities.log_traceback:227 - Type: Unclassified
Class: PermissionError
Message: [Errno 1] Operation not permitted: '/anaconda/envs/azureml_py38/lib/python3.8/site-packages/nimbusml/internal/libs/pybridge.so'
Traceback:
  File "_model_download_utilities.py", line 172, in _load_automl_model
    fitted_model = pickle.load(model_file)  # type: Optional[Any]
  File "__init__.py", line 8, in <module>
    from .data_transformer import DataTransformer, TransformerAndMapper
  File "data_transformer.py", line 56, in <module>
    from azureml.automl.runtime.featurizer.transformer.categorical import LabelEncoderTransformer
  File "__init__.py", line 7, in <module>
    from .categorical import CategoricalFeaturizers, CatImputer, LabelEncoderTransformer, \
  File "__init__.py", line 8, in <module>
    from .categorical_featurizers import CategoricalFeaturizers
  File "categorical_featurizers.py", line 8, in <module>
    from nimbusml.feature_extraction.categorical import OneHotVectorizer as NimbusMLOneHotVectorizer
  File "__init__.py", line 33, in <module>
    os.chmod(dotso, 0o755)

ExceptionTarget: Unspecified
2023-02-11 13:11:53.787 - CRITICAL - 7299 - azureml.train.automl._model_download_utilities.log_traceback:227 - Type: Unclassified
Class: PermissionError
Message: [Errno 1] Operation not permitted: '/anaconda/envs/azureml_py38/lib/python3.8/site-packages/nimbusml/internal/libs/pybridge.so'
Traceback:
  File "telemetry_activity_logger.py", line 58, in _log_activity
    yield
  File "_model_download_utilities.py", line 80, in _download_automl_model
    model = _load_automl_model(model_path, suffix)
  File "_model_download_utilities.py", line 172, in _load_automl_model
    fitted_model = pickle.load(model_file)  # type: Optional[Any]
  File "__init__.py", line 8, in <module>
    from .data_transformer import DataTransformer, TransformerAndMapper
  File "data_transformer.py", line 56, in <module>
    from azureml.automl.runtime.featurizer.transformer.categorical import LabelEncoderTransformer
  File "__init__.py", line 7, in <module>
    from .categorical import CategoricalFeaturizers, CatImputer, LabelEncoderTransformer, \
  File "__init__.py", line 8, in <module>
    from .categorical_featurizers import CategoricalFeaturizers
  File "categorical_featurizers.py", line 8, in <module>
    from nimbusml.feature_extraction.categorical import OneHotVectorizer as NimbusMLOneHotVectorizer
  File "__init__.py", line 33, in <module>
    os.chmod(dotso, 0o755)

ExceptionTarget: Unspecified
2023-02-11 13:11:53.787 - INFO - 7299 - azureml.train.automl._model_download_utilities._log_activity:89 - ActivityCompleted: Activity=DownloadModel, HowEnded=Failure, Duration=1012.73[ms]
2023-02-11 13:11:53.788 - CRITICAL - 7299 - azureml.train.automl.run.log_traceback:227 - Type: Unclassified
Class: PermissionError
Message: [Errno 1] Operation not permitted: '/anaconda/envs/azureml_py38/lib/python3.8/site-packages/nimbusml/internal/libs/pybridge.so'
Traceback:
  File "telemetry_activity_logger.py", line 58, in _log_activity
    yield
  File "run.py", line 718, in get_output
    fitted_model = _download_automl_model(curr_run, model_name)
  File "_model_download_utilities.py", line 80, in _download_automl_model
    model = _load_automl_model(model_path, suffix)
  File "_model_download_utilities.py", line 172, in _load_automl_model
    fitted_model = pickle.load(model_file)  # type: Optional[Any]
  File "__init__.py", line 8, in <module>
    from .data_transformer import DataTransformer, TransformerAndMapper
  File "data_transformer.py", line 56, in <module>
    from azureml.automl.runtime.featurizer.transformer.categorical import LabelEncoderTransformer
  File "__init__.py", line 7, in <module>
    from .categorical import CategoricalFeaturizers, CatImputer, LabelEncoderTransformer, \
  File "__init__.py", line 8, in <module>
    from .categorical_featurizers import CategoricalFeaturizers
  File "categorical_featurizers.py", line 8, in <module>
    from nimbusml.feature_extraction.categorical import OneHotVectorizer as NimbusMLOneHotVectorizer
  File "__init__.py", line 33, in <module>
    os.chmod(dotso, 0o755)

ExceptionTarget: Unspecified
2023-02-11 13:11:53.788 - INFO - 7299 - azureml.train.automl.run._log_activity:89 - ActivityCompleted: Activity=GetOutput, HowEnded=Failure, Duration=1383.01[ms]
2023-02-11 14:04:41.480 - INFO - 7299 - azureml.train.automl.run._log_activity:55 - ActivityStarted: GetOutput
2023-02-11 14:04:41.502 - INFO - 7299 - azureml.train.automl.run._log_activity:55 - ActivityStarted: GetOutput
2023-02-11 14:04:41.522 - INFO - 7299 - azureml.train.automl.run._log_activity:55 - ActivityStarted: GetChildren
2023-02-11 14:04:41.668 - INFO - 7299 - azureml.train.automl.run._log_activity:89 - ActivityCompleted: Activity=GetChildren, HowEnded=Success, Duration=145.94[ms]
2023-02-11 14:04:41.741 - INFO - 7299 - azureml.train.automl.run._log_activity:89 - ActivityCompleted: Activity=GetOutput, HowEnded=Success, Duration=239.08[ms]
2023-02-11 14:04:41.741 - INFO - 7299 - azureml.train.automl._model_download_utilities._log_activity:55 - ActivityStarted: DownloadModel
2023-02-11 14:04:42.313 - CRITICAL - 7299 - azureml.train.automl._model_download_utilities.log_traceback:227 - Type: Unclassified
Class: PermissionError
Message: [Errno 1] Operation not permitted: '/anaconda/envs/azureml_py38/lib/python3.8/site-packages/nimbusml/internal/libs/pybridge.so'
Traceback:
  File "_model_download_utilities.py", line 172, in _load_automl_model
    fitted_model = pickle.load(model_file)  # type: Optional[Any]
  File "__init__.py", line 8, in <module>
    from .data_transformer import DataTransformer, TransformerAndMapper
  File "data_transformer.py", line 56, in <module>
    from azureml.automl.runtime.featurizer.transformer.categorical import LabelEncoderTransformer
  File "__init__.py", line 7, in <module>
    from .categorical import CategoricalFeaturizers, CatImputer, LabelEncoderTransformer, \
  File "__init__.py", line 8, in <module>
    from .categorical_featurizers import CategoricalFeaturizers
  File "categorical_featurizers.py", line 8, in <module>
    from nimbusml.feature_extraction.categorical import OneHotVectorizer as NimbusMLOneHotVectorizer
  File "__init__.py", line 33, in <module>
    os.chmod(dotso, 0o755)

ExceptionTarget: Unspecified
2023-02-11 14:04:42.512 - CRITICAL - 7299 - azureml.train.automl._model_download_utilities.log_traceback:227 - Type: Unclassified
Class: PermissionError
Message: [Errno 1] Operation not permitted: '/anaconda/envs/azureml_py38/lib/python3.8/site-packages/nimbusml/internal/libs/pybridge.so'
Traceback:
  File "telemetry_activity_logger.py", line 58, in _log_activity
    yield
  File "_model_download_utilities.py", line 80, in _download_automl_model
    model = _load_automl_model(model_path, suffix)
  File "_model_download_utilities.py", line 172, in _load_automl_model
    fitted_model = pickle.load(model_file)  # type: Optional[Any]
  File "__init__.py", line 8, in <module>
    from .data_transformer import DataTransformer, TransformerAndMapper
  File "data_transformer.py", line 56, in <module>
    from azureml.automl.runtime.featurizer.transformer.categorical import LabelEncoderTransformer
  File "__init__.py", line 7, in <module>
    from .categorical import CategoricalFeaturizers, CatImputer, LabelEncoderTransformer, \
  File "__init__.py", line 8, in <module>
    from .categorical_featurizers import CategoricalFeaturizers
  File "categorical_featurizers.py", line 8, in <module>
    from nimbusml.feature_extraction.categorical import OneHotVectorizer as NimbusMLOneHotVectorizer
  File "__init__.py", line 33, in <module>
    os.chmod(dotso, 0o755)

ExceptionTarget: Unspecified
2023-02-11 14:04:42.512 - INFO - 7299 - azureml.train.automl._model_download_utilities._log_activity:89 - ActivityCompleted: Activity=DownloadModel, HowEnded=Failure, Duration=770.83[ms]
2023-02-11 14:04:42.513 - CRITICAL - 7299 - azureml.train.automl.run.log_traceback:227 - Type: Unclassified
Class: PermissionError
Message: [Errno 1] Operation not permitted: '/anaconda/envs/azureml_py38/lib/python3.8/site-packages/nimbusml/internal/libs/pybridge.so'
Traceback:
  File "telemetry_activity_logger.py", line 58, in _log_activity
    yield
  File "run.py", line 718, in get_output
    fitted_model = _download_automl_model(curr_run, model_name)
  File "_model_download_utilities.py", line 80, in _download_automl_model
    model = _load_automl_model(model_path, suffix)
  File "_model_download_utilities.py", line 172, in _load_automl_model
    fitted_model = pickle.load(model_file)  # type: Optional[Any]
  File "__init__.py", line 8, in <module>
    from .data_transformer import DataTransformer, TransformerAndMapper
  File "data_transformer.py", line 56, in <module>
    from azureml.automl.runtime.featurizer.transformer.categorical import LabelEncoderTransformer
  File "__init__.py", line 7, in <module>
    from .categorical import CategoricalFeaturizers, CatImputer, LabelEncoderTransformer, \
  File "__init__.py", line 8, in <module>
    from .categorical_featurizers import CategoricalFeaturizers
  File "categorical_featurizers.py", line 8, in <module>
    from nimbusml.feature_extraction.categorical import OneHotVectorizer as NimbusMLOneHotVectorizer
  File "__init__.py", line 33, in <module>
    os.chmod(dotso, 0o755)

ExceptionTarget: Unspecified
2023-02-11 14:04:42.513 - INFO - 7299 - azureml.train.automl.run._log_activity:89 - ActivityCompleted: Activity=GetOutput, HowEnded=Failure, Duration=1033.5[ms]
